extends RefCounted
class_name WeaponIcons

# Which picture a weapon gets, and the colour of its quality tier -- shared by the
# Inventory's weapon cards and the shop rows.
#
# Every weapon type has a 32x32 icon per material (assets/weapons/<base>_<material>.png,
# generated by tools/gen_weapon_icons.gd), so a Golden Spear and a Bone Spear are
# different pictures. On top of that, Legendary and Mythic weapons can have
# hand-made art: drop a 32x32 PNG into assets/weapons/ named
#
#   legendary_<base>.png          e.g. legendary_spear.png, legendary_battle_axe.png
#   legendary_<base>_<material>.png   (optional: a version per material)
#   mythic_<base>.png             (same idea for the named Mythic artifacts)
#
# and it is used instead, with no code change. A file that is missing simply falls
# back to the generated icon, so art can be added one weapon at a time.

const WeaponsScript := preload("res://scripts/Weapons.gd")

# Where the icons live. A variable (not a const) only so the tests can point it at
# a scratch folder.
static var dir := "res://assets/weapons"

# One colour per quality tier, worst to best. Legendary (red) and Mythic (gold) also
# get a glow -- see GLOWING_TIERS.
const TIER_COLORS := {
	"Broken": Color(0.42, 0.4, 0.4),
	"Worn": Color(0.68, 0.68, 0.72),
	"Fine": Color(0.36, 0.78, 0.42),
	"Masterwork": Color(0.38, 0.62, 1.0),
	"Legendary": Color(0.96, 0.2, 0.2),
	"Mythic": Color(1.0, 0.82, 0.25),
}
const GLOWING_TIERS := ["Legendary", "Mythic"]
const CLUB_COLOR := Color(0.55, 0.5, 0.45)

static func tier_color(weapon: Dictionary) -> Color:
	return TIER_COLORS.get(weapon.get("tier_name", ""), CLUB_COLOR)

static func has_glow(weapon: Dictionary) -> bool:
	return weapon.get("tier_name", "") in GLOWING_TIERS

# The tier as shown on a card ("Starter" for the Club, which has none).
static func tier_label(weapon: Dictionary) -> String:
	return weapon.get("tier_name", "Starter")

# The weapon's name without its tier, since the card shows the tier as a coloured
# tag: "Wooden Spear", "Battle Axe", "Club". A Mythic keeps its own artifact name.
static func display_name(weapon: Dictionary) -> String:
	if weapon.get("tier_name", "") == "Mythic" or weapon.get("id", "") == "club":
		return weapon.get("name", "")
	var base: Dictionary = WeaponsScript.get_base_type(weapon)
	var base_name: String = base.get("name", weapon.get("name", ""))
	var material_id: String = weapon.get("material_id", "steel")
	if material_id == "steel":
		return base_name
	return "%s %s" % [weapon.get("material_name", ""), base_name]

# Every place the icon might be, best first.
static func candidate_paths(weapon: Dictionary) -> Array:
	var base: String = weapon.get("icon", "")
	var tier: String = weapon.get("tier_name", "")
	var material: String = weapon.get("material_id", "gold" if tier == "Mythic" else "steel")
	var paths: Array = []
	if base == "club":
		paths.append("%s/club.png" % dir)
	if tier == "Legendary" or tier == "Mythic":
		paths.append("%s/%s_%s_%s.png" % [dir, tier.to_lower(), base, material])
		paths.append("%s/%s_%s.png" % [dir, tier.to_lower(), base])
	paths.append("%s/%s_%s.png" % [dir, base, material])
	paths.append("%s/%s_steel.png" % [dir, base])
	# The old 20px icon, in case none of the above exists.
	paths.append("res://assets/weapon_%s.png" % base)
	return paths

static func path_for(weapon: Dictionary) -> String:
	for path in candidate_paths(weapon):
		if ResourceLoader.exists(path) or FileAccess.file_exists(path):
			return path
	return ""

static func texture_for(weapon: Dictionary) -> Texture2D:
	var path := path_for(weapon)
	if path == "":
		return null
	# Normally an imported resource; a PNG just dropped into the folder (the editor
	# has not imported it yet) is read straight from disk so it still shows up.
	if ResourceLoader.exists(path):
		return load(path)
	var img := Image.load_from_file(path)
	return ImageTexture.create_from_image(img) if img != null else null
