extends SceneTree

# The 32x32 weapon icons (assets/weapons/, generated by tools/gen_weapon_icons.gd),
# the drop-in slot for hand-made Legendary/Mythic art, the per-tier palette, and
# the Inventory's weapon cards built from them (tier border, Legendary/Mythic
# glow, EQUIPPED tag, damage, Might lock, best-tier-first order).

const BASES := ["spear", "greatsword", "hammer", "battle_axe", "dagger", "bow", "knuckle_gloves", "hand_picks"]
const MATERIALS := ["wood", "steel", "gold", "bone", "silver", "obsidian"]

func _collect_labels(node: Node) -> Array:
	var texts := []
	if node is Label:
		texts.append(node.text)
	for child in node.get_children():
		texts.append_array(_collect_labels(child))
	return texts

func _cards(panel) -> Array:
	var found := []
	_find_cards(panel.tab_containers.Weapons, panel.WEAPON_CELL_SIZE, found)
	return found

# Depth-first in tree order, so the cards come back in the order they are laid out.
func _find_cards(node: Node, card_size: Vector2, found: Array) -> void:
	if node is Button and node.custom_minimum_size == card_size:
		found.append(node)
		return
	for child in node.get_children():
		_find_cards(child, card_size, found)

func _init() -> void:
	# Fixed seed: every random roll below repeats run to run, so a changed result
	# is a real change, not luck.
	seed(20260926)
	var icons_script = load("res://scripts/WeaponIcons.gd")
	var weapons_script = load("res://scripts/Weapons.gd")

	# --- The generated icon set ---
	var missing := 0
	var wrong_size := 0
	for base in BASES:
		for material in MATERIALS:
			var path := "res://assets/weapons/%s_%s.png" % [base, material]
			if not ResourceLoader.exists(path):
				missing += 1
				continue
			var img: Image = (load(path) as Texture2D).get_image()
			if img.get_width() != 32 or img.get_height() != 32:
				wrong_size += 1
	var club_ok: bool = ResourceLoader.exists("res://assets/weapons/club.png") and (load("res://assets/weapons/club.png") as Texture2D).get_width() == 32
	print("all 8 weapon types x 6 materials exist as 32x32 icons: missing=%d wrong_size=%d club=%s (expected 0, 0, true)" % [missing, wrong_size, club_ok])

	# --- Which icon a weapon gets ---
	var gold_spear: Dictionary = weapons_script.get_owned_variant("spear_fine_gold")
	var wood_spear: Dictionary = weapons_script.get_owned_variant("spear_worn_wood")
	print("material picks the picture: gold=%s wood=%s (expected .../spear_gold.png, .../spear_wood.png)" % [
		icons_script.path_for(gold_spear).get_file(), icons_script.path_for(wood_spear).get_file()
	])
	print("the Club has its own icon: %s (expected club.png)" % [icons_script.path_for(weapons_script.get_owned_variant("club")).get_file()])
	var legendary_axe: Dictionary = weapons_script.get_owned_variant("battle_axe_legendary_bone")
	var mythic_dagger: Dictionary = weapons_script.get_owned_variant("dagger_mythic")
	print("Legendary looks for hand-made art first, most specific first: %s (expected [legendary_battle_axe_bone, legendary_battle_axe, battle_axe_bone, battle_axe_steel, ...])" % [
		icons_script.candidate_paths(legendary_axe).slice(0, 4).map(func(p): return p.get_file().get_basename())
	])
	print("a Mythic (no material of its own) falls back to gold: %s (expected [mythic_dagger_gold, mythic_dagger, dagger_gold, ...])" % [
		icons_script.candidate_paths(mythic_dagger).slice(0, 3).map(func(p): return p.get_file().get_basename())
	])
	print("with no hand-made art present, Legendary still gets the generated icon: %s (expected battle_axe_bone.png)" % [icons_script.path_for(legendary_axe).get_file()])

	# Hand-made art dropped into the folder is picked up (and needs no editor import).
	var scratch := "user://weapon_icon_test"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(scratch))
	for name in ["legendary_battle_axe", "legendary_dagger_gold", "generic_only"]:
		var pic := Image.create(32, 32, false, Image.FORMAT_RGBA8)
		pic.fill(Color(1, 0, 0))
		pic.save_png("%s/%s.png" % [scratch, name])
	var real_dir: String = icons_script.dir
	icons_script.dir = scratch
	print("a hand-made legendary_<base>.png is used for a Legendary of any material: %s (expected legendary_battle_axe.png)" % [icons_script.path_for(legendary_axe).get_file()])
	var legendary_gold_dagger: Dictionary = weapons_script.get_owned_variant("dagger_legendary_gold")
	var legendary_bone_dagger: Dictionary = weapons_script.get_owned_variant("dagger_legendary_bone")
	print("...and a per-material file beats it for that material: gold=%s bone=%s (expected legendary_dagger_gold.png, weapon_dagger.png: no generated icons in the scratch folder, so the old 20px one)" % [
		icons_script.path_for(legendary_gold_dagger).get_file(), icons_script.path_for(legendary_bone_dagger).get_file()
	])
	var raw_texture: Texture2D = icons_script.texture_for(legendary_axe)
	print("a PNG the editor hasn't imported still loads: %s size=%s (expected true, (32, 32))" % [raw_texture != null, raw_texture.get_size() if raw_texture != null else "none"])
	icons_script.dir = real_dir
	print("a non-legendary weapon ignores hand-made art: %s (expected spear_gold.png)" % [icons_script.path_for(gold_spear).get_file()])

	# --- Tier colours ---
	var seen := {}
	for tier in weapons_script.TIERS:
		seen[icons_script.TIER_COLORS[tier.tier_name].to_html()] = true
	var red: Color = icons_script.TIER_COLORS["Legendary"]
	print("every tier has its own colour (6 distinct): %d (expected 6)" % [seen.size()])
	print("Legendary is red: r=%.2f g=%.2f b=%.2f (expected r high, g and b low)" % [red.r, red.g, red.b])
	print("only Legendary and Mythic glow: %s (expected [Legendary, Mythic])" % [
		weapons_script.TIERS.filter(func(t): return icons_script.has_glow({"tier_name": t.tier_name})).map(func(t): return t.tier_name)
	])

	# --- Names ---
	print("names drop the tier (shown as a tag) and keep the material: %s | %s | %s | %s (expected Wooden Spear | Spear | Golden Greatsword | the Great Toothpicke)" % [
		icons_script.display_name(wood_spear), icons_script.display_name(weapons_script.get_owned_variant("spear_masterwork_steel")),
		icons_script.display_name(weapons_script.get_owned_variant("greatsword_fine_gold")), icons_script.display_name(weapons_script.get_owned_variant("spear_mythic"))
	])
	print("the Club is just Club, tagged Starter: %s / %s (expected Club / Starter)" % [
		icons_script.display_name(weapons_script.get_owned_variant("club")), icons_script.tier_label(weapons_script.get_owned_variant("club"))
	])

	# --- The Inventory cards ---
	var main = load("res://Main.tscn").instantiate()
	root.add_child(main)
	await physics_frame
	await physics_frame
	var player = main.player
	for e in main.get_tree().get_nodes_in_group("enemies"):
		e.set_physics_process(false)
	player.owned_weapons = {}
	for id in ["club", "spear_fine_steel", "spear_worn_wood", "battle_axe_legendary_steel", "spear_mythic", "greatsword_masterwork_gold", "dagger_broken_bone"]:
		player.owned_weapons[id] = true
	player.weapon_enchantments["greatsword_masterwork_gold"] = "ember"
	player.weapon_upgrade_levels["spear_fine_steel"] = 2
	player.stat_might = 30
	player.attack_damage = 10
	player._equip_weapon(weapons_script.get_owned_variant("spear_fine_steel"))
	var panel = main.inventory_panel
	panel.open(player)
	var cards: Array = _cards(panel)
	print("one card per owned weapon, all the same size: %d cards (expected 7), sizes=%s (expected all %s)" % [
		cards.size(), cards.map(func(c): return c.custom_minimum_size).all(func(s): return s == panel.WEAPON_CELL_SIZE), panel.WEAPON_CELL_SIZE
	])
	var order: Array = cards.map(func(c): return _collect_labels(c)[0])
	print("best tier first, the Club last: %s (expected Mythic, Legendary, Masterwork, Fine +2, Worn, Broken, Starter)" % [", ".join(order)])

	var legendary_card: Button = cards[1]
	var legendary_box: StyleBoxFlat = legendary_card.get_theme_stylebox("normal")
	var fine_card: Button = cards[3]
	var fine_box: StyleBoxFlat = fine_card.get_theme_stylebox("normal")
	var mythic_box: StyleBoxFlat = cards[0].get_theme_stylebox("normal")
	print("a Legendary card has a red border and a glow: border=%s glow=%d z=%d (expected red, > 0, above its neighbours)" % [
		legendary_box.border_color == icons_script.TIER_COLORS["Legendary"], legendary_box.shadow_size, legendary_card.z_index
	])
	print("...a Mythic one a gold border and a bigger glow: gold=%s glow=%d (expected true, > the Legendary's)" % [
		mythic_box.border_color == icons_script.TIER_COLORS["Mythic"], mythic_box.shadow_size
	])
	print("...a Fine card is green with no glow: green=%s glow=%d (expected true, 0)" % [fine_box.border_color == icons_script.TIER_COLORS["Fine"], fine_box.shadow_size])

	var equipped_texts: Array = _collect_labels(fine_card)
	print("the equipped card says so, shows its Blacksmith level and damage: %s (expected EQUIPPED, 'Fine +2', DMG %d)" % [
		equipped_texts, player.weapon_damage_preview(weapons_script.get_owned_variant("spear_fine_steel"))
	])
	var masterwork_texts: Array = _collect_labels(cards[2])
	print("a card shows its Might requirement and rune: %s (expected MGT 8 and Rune of Flame)" % [masterwork_texts])
	print("the damage number is your Strength times the weapon: %d (expected %d)" % [
		player.weapon_damage_preview(weapons_script.get_owned_variant("greatsword_masterwork_gold")),
		int(round(10 * player._apply_enchantment_to_weapon(weapons_script.get_owned_variant("greatsword_masterwork_gold")).damage_mult))
	])

	# Might lock: shown red, and equipping is refused like in the shop.
	player.stat_might = 0
	panel._refresh()
	await process_frame  # the old cards are only freed at the end of the frame
	cards = _cards(panel)
	var locked_texts: Array = _collect_labels(cards[1])
	var locked_tooltip: String = cards[1].tooltip_text
	cards[1].pressed.emit()
	print("with too little Might the card shows the requirement in red and won't equip: labels=%s tooltip_mentions_might=%s equipped=%s (expected MGT 16, true, spear_fine_steel)" % [
		locked_texts, locked_tooltip.contains("Needs 16 Might"), player.current_weapon_base.id
	])
	player.stat_might = 30
	panel._refresh()
	await process_frame  # the old cards are only freed at the end of the frame
	cards = _cards(panel)
	cards[1].pressed.emit()
	print("...and equips once you have it: %s (expected battle_axe_legendary_steel)" % [player.current_weapon_base.id])

	panel.close()
	DirAccess.remove_absolute(ProjectSettings.globalize_path("%s/legendary_battle_axe.png" % scratch))
	DirAccess.remove_absolute(ProjectSettings.globalize_path("%s/legendary_dagger_gold.png" % scratch))
	DirAccess.remove_absolute(ProjectSettings.globalize_path("%s/generic_only.png" % scratch))
	quit()
